In [9]:
#import necessary libraries and load datasets
import pandas as pd

sentiment = pd.read_csv("fear_greed_index.csv")
trades = pd.read_csv("historical_data.csv")

In [ ]:
# print dataset shapes
print("Sentiment dataset shape:", sentiment.shape)
print("Trades dataset shape:", trades.shape)

Sentiment dataset shape: (2644, 4)
Trades dataset shape: (211224, 16)

In [9]:
# Check for missing values
print("sentiment data missing values:\n", sentiment.isnull().sum())
print("trades data missing values:\n", trades.isnull().sum())

sentiment data missing values:
 timestamp         0
value             0
classification    0
date              0
dtype: int64
trades data missing values:
 Account             0
Coin                0
Execution Price     0
Size Tokens         0
Size USD            0
Side                0
Timestamp IST       0
Start Position      0
Direction           0
Closed PnL          0
Transaction Hash    0
Order ID            0
Crossed             0
Fee                 0
Trade ID            0
Timestamp           0
dtype: int64

In [ ]:
#check for duplicates
sentiment.duplicated().sum()
trades.duplicated().sum()

np.int64(0)

In [17]:
trades.dtypes

Account              object
Coin                 object
Execution Price     float64
Size Tokens         float64
Size USD            float64
Side                 object
Timestamp IST        object
Start Position      float64
Direction            object
Closed PnL          float64
Transaction Hash     object
Order ID              int64
Crossed                bool
Fee                 float64
Trade ID            float64
Timestamp           float64
dtype: object

In [18]:
sentiment.dtypes

timestamp          int64
value              int64
classification    object
date              object
dtype: object

In [26]:
#converting timestamps
sentiment['datetime'] = pd.to_datetime(sentiment['timestamp'], unit='s')
sentiment['date'] = sentiment['datetime'].dt.date
sentiment[['timestamp','datetime','date']].head()

    timestamp            datetime        date
0  1517463000 2018-02-01 05:30:00  2018-02-01
1  1517549400 2018-02-02 05:30:00  2018-02-02
2  1517635800 2018-02-03 05:30:00  2018-02-03
3  1517722200 2018-02-04 05:30:00  2018-02-04
4  1517808600 2018-02-05 05:30:00  2018-02-05

In [ ]:
#converting timestamps
trades['datetime'] = pd.to_datetime(trades['Timestamp'], unit='ms')
trades['date'] = trades['datetime'].dt.date

trades[['Timestamp','datetime','date']].head()

      Timestamp            datetime        date
0  1.730000e+12 2024-10-27 03:33:20  2024-10-27
1  1.730000e+12 2024-10-27 03:33:20  2024-10-27
2  1.730000e+12 2024-10-27 03:33:20  2024-10-27
3  1.730000e+12 2024-10-27 03:33:20  2024-10-27
4  1.730000e+12 2024-10-27 03:33:20  2024-10-27

In [27]:
merged = pd.merge(trades, sentiment[['date','classification']], on='date', how='left')
merged[['date','classification']].head()

         date classification
0  2024-10-27          Greed
1  2024-10-27          Greed
2  2024-10-27          Greed
3  2024-10-27          Greed
4  2024-10-27          Greed